export const AGREGAR_VINO = "AGREGAR_VINO";
export const AGREGAR_VINO_EXITO = "AGREGAR_VINO_EXITO";
export const AGREGAR_VINO_ERROR = "AGREGAR_VINO_ERROR";

export const GET_VINOS = "GET_VINOS";
export const GET_VINOS_EXITO = "GET_VINOS_EXITO";
export const GET_VINOS_ERROR = "GET_VINOS_ERROR";

export const QUITAR_VINO = "QUITAR_VINO";
export const QUITAR_VINO_EXITO = "QUITAR_VINO_EXITO";
export const QUITAR_VINO_ERROR = "QUITAR_VINO_ERROR";
