export const AGREGAR_CERVEZA = "AGREGAR_CERVEZA";
export const AGREGAR_CERVEZA_EXITO = "AGREGAR_CERVEZA_EXITO";
export const AGREGAR_CERVEZA_ERROR = "AGREGAR_CERVEZA_ERROR";

export const GET_CERVEZAS = "GET_CERVEZAS";
export const GET_CERVEZAS_EXITO = "GET_CERVEZAS_EXITO";
export const GET_CERVEZAS_ERROR = "GET_CERVEZAS_ERROR";

export const QUITAR_CERVEZA = "QUITAR_CERVEZA";
export const QUITAR_CERVEZA_EXITO = "QUITAR_CERVEZA_EXITO";
export const QUITAR_CERVEZA_ERROR = "QUITAR_CERVEZA_ERROR";
